services:
  test-app:
    build:
      context: assets/aws-ses-send-mail-app
      dockerfile: Dockerfile
    environment:
      AWS_SES_ENDPOINT: http://ses-gateway:8081
    depends_on:
      - ses-gateway
      - mailhog
  ses-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USER: mailhog
      SMTP_PASS: mailhog

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    environment:
      MH_AUTH_FILE: /mailhog.auth
    volumes:
      - ./assets/mailhog/auth.cfg:/mailhog.auth:ro

    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui